---
- hosts: leaf
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
  tasks:

  - name: configurable backup path
    arista.eos.eos_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}.cfg"
