---
- name: BGP Change Observation
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Send notification message via Mattermost
      community.general.mattermost:
       url: http://podman-host:8065
       api_key: bwqyj6tnrtne7n53x99xzk3msa   ######### YOUR API KEY #########
       attachments:
         - text: "!!!!!! ALERT !!!!!!"
           color: '#ff00dd'
           title: BGP ERROR
           fields:
            - title: Issue Detected
              value: "BGP Session: {{ ansible_eda.event.bgp_state }}"
              short: true
            - title: Potential Problem
              value: "Problematic node/path: {{ ansible_eda.event.bgp_prob_neighbor }}"
              short: true
            - title: Message
              value: "Event detected issue, human intervention is required, Dave"
              short: true
      delegate_to: localhost
